PRINTER_BASE_URL = 'http://192.168.0.233'
PRINTER_PAGE_URL = 'http://192.168.0.233'
PRINTER_STREAM_URL = 'http://192.168.0.233/webcam/?action=stream'

LAYOUT_TEXT_OFF = 'Off'
LAYOUT_TEXT_ON = 'On'
LAYOUT_BUTTON_WIDTH = 10
LAYOUT_BUTTON_HEIGHT = 5
LAYOUT_FONT_SIZE = 10
LAYOUT_BIG_FONT_SIZE = 12
LAYOUT_SMALL_FONT_SIZE = 8
LAYOUT_FONT_FAMILY = 'Helvetica'
LAYOUT_LABEL_HEIGHT = 1
LAYOUT_FRAME_WIDTH = 100
LAYOUT_FRAME_HEIGHT = 50
LAYOUT_FRAME_LEFT_RIGHT_RATIO = 0.7
